### ISSUE TITLE
feature req: ability to scroll emojis directly after opening (seamlessly gesture)

### ISSUE THREAD

**Issue by efstathiosntonas** [SimformSolutionsPvtLtd/react-native-reactions#27]
Hi, thank you for this library. One thing I've noticed is that the process is broken down into 3 steps:
1. Long press the button
2. Lift finger from screen
3. Hold one emoji and then move finger left-right and release gesture to select.

Can this be done seamlessly eg:
1. Long press button
2. Without releasing the gesture move the finger in the emojis and when gesture is released select the desired emoji.

What Facebook is doing is to have 2 states:
* First state is to display the emojis on single tap and then select the emoji (no ability to long press the emojis)
* Second state is the one I described above, long press the button and then seamlessly move your finger to the desired emoji in "one go"

I hope I made it clear.

**Comment by efstathiosntonas** [comment]
Hi, any updates on this one? Thanks!

**Comment by ravir-simform** [comment]
Thank you @efstathiosntonas for showing your interest in this library and tried it out. Currently, we are having less bandwidth but as soon as we have someone to work on this, we will take it on priority. Meanwhile, if you get some time and wanted to contribute than that will be really helpful for us.

**Comment by efstathiosntonas** [comment]
Hi, I've seen the the PR about this issue has been closed. Do you have any updates about ETA? Thanks

**Comment by mukesh-simform** [comment]
Currently, we're testing all possible cases and next week we'll plan one release. Stay tuned!

**Comment by aditijain2606** [comment]
This behaviour is fixed for normal views but if I use it with bottom sheets I have to lift my finger and then select any emoji to enable it. Can we do something about it?
