### ISSUE TITLE
[BUG]: on slide emojis are not showing

### ISSUE THREAD

**Issue by sunilanumolu** [SimformSolutionsPvtLtd/react-native-reactions#28]
On finger slide on the emojis card box, emojis are not showing
any idea, how to fix this
let me know if more details are needed
P.S. thanks for the library btw

**Comment by sunilanumolu** [comment]
Can anyone please respond on this, I'm still facing this issue

**Comment by ravir-simform** [comment]
@sunilanumolu Thanks for reporting this issue? Can you please share a video of issue you are facing? Or if you can elaborate more, it will be helpful for us to resolve.

**Comment by sunilanumolu** [comment]
Hi, 

I'm using modal type and wrapped ReactionProvider on my root component of the app.
Issues: 
1. when I'm sliding over the emojis, they disappear and when selected emoji also they disappear
2. I cannot close the container unless I select an emoji for sure

It'll will be really helpful if you can provide solution for this, I tried but nothing is resolving these issues.

Please find the below video attachment for understanding the issue.
https://user-images.githubusercontent.com/32481223/211154601-a575f700-d0ca-4ded-a590-adec719700db.mp4

versions: 
"react": "17.0.1",
"react-native": "0.65.3",
"react-native-reactions": "^0.0.1",

P.S. Thank You.

**Comment by vishva-simform** [comment]
Hi @sunilanumolu Thank you for providing the reference video! Could you please share the device details you're using?

**Comment by vishva-simform** [comment]
Hi @sunilanumolu We have tried to solve your problem. The changes are in the slide_emoji_issue branch , so you have to make the following change in package.json file and after that re-install node modules to see the result. 

**"react-native-reactions": "github:SimformSolutionsPvtLtd/react-native-reactions#slide_emoji_issue",**

Hope this helps! Thanks.

**Comment by sunilanumolu** [comment]
Hi @vishva-simform, I tried **slide_emoji_issue** branch change, still the issue persists, I'm not able to figure why it's occurring. 
I'm using react-native-reanimated: 2.2.4, is it because of this?

Thank you for your efforts. If you can please check again it'll be very helpful.

P.S. THANKS

**Comment by virajpsimformsolutions** [comment]
@sunilanumolu 

react-native-reanimated: 2.2.4 version is more then 1 year older. Can you please upgrade reanimated latest version to 2.13.0? let us know if still issue is there after update.

**Comment by maoapp** [comment]
> Hi @sunilanumolu We have tried to solve your problem. Until we release new version you can check out the branch named **slide_emoji_issue**, To see the result you have to make the following change in package.json file and after that re-install node modules.
> 
> **"react-native-reactions": "github:SimformSolutionsPvtLtd/react-native-reactions#slide_emoji_issue",**
> 
> Hope this helps! Thanks.

When I tried to apply this I got this 
<img width="355" alt="image" src="https://user-images.githubusercontent.com/19539930/212777844-9006323c-fdb3-4d0e-86f5-4785aa5860a1.png">
