### ISSUE TITLE
Error: Reading from `_value` directly is only possible on the UI runtime while using reanimated 3

### ISSUE THREAD

**Issue by efstathiosntonas** [SimformSolutionsPvtLtd/react-native-reactions#30]
After upgrading to react-native-reanimated it throws this error: 

`Error: Reading from "_value" directly is only possible on the UI runtime`

![simulator_screenshot_A5DE4FC7-F77F-40B5-8640-EA012C516FE1](https://user-images.githubusercontent.com/717975/222696856-db6145a6-cc13-4e08-a306-33eecb4edd85.png)

I'm using `react-native@0.71.3`

**Comment by efstathiosntonas** [comment]
The problem relies in this line: https://github.com/SimformSolutionsPvtLtd/react-native-reactions/blob/98872c19e8dcae89c29566fd72bf96d13a5e9788/src/components/EmojiItem/hooks/useEmojiItem.ts#L49

**Comment by vikrant-k-simformsolutions** [comment]
> The problem relies in this line:
> 
> https://github.com/SimformSolutionsPvtLtd/react-native-reactions/blob/98872c19e8dcae89c29566fd72bf96d13a5e9788/src/components/EmojiItem/hooks/useEmojiItem.ts#L49
> 
> Why it's `_value` and not `value`? 🤔 After swapping it to `.value` it works just fine.

Hi @efstathiosntonas, Thank you for the pointing out the cause. We will surly take a look and include version specific fixes into our next release.

**Comment by efstathiosntonas** [comment]
Thank you @vikrant-k-simformsolutions !
