### ISSUE TITLE
Disable show popup with emojis by a single click

### ISSUE THREAD

**Issue by aklevko** [SimformSolutionsPvtLtd/react-native-reactions#36]
Hello

First of all thanks for the library

Have a couple of questions:

1. How to disable showing popup with emojis by a single click and leave only long press. I see there is prop showPopupType it has to be default behavior but it doesn't work. An interesting point, the click does not always work, but very often, especially when emoji not selected yet.

2. If to use long press and after that do not select emoji then the popup is hidden. How to keep popup visible after long press until user has selected emoji or clicked outside popup with emojis?

**Comment by mukesh-simform** [comment]
We've recently released a new version that should address the issue, Please try using the new version. if you continue to encounter the issue, feel free to reopen the existing ticket or create a new one.
