### ISSUE TITLE
[BUG]: Modal popup doesn't always appear

### ISSUE THREAD

**Issue by KodDaniel** [SimformSolutionsPvtLtd/react-native-reactions#37]
First of all, thanks for the neat library. We are having a problem though. The modal function is very good, but the popup doesn't always appear when it should. This applies regardless of whether we set "default" or "onPress" for the showPopupType-property.

However, the popup always appears if we set the type-property to "default" instead of "modal". Is this a problem you are familiar with or have some good workaround for?

Again, thanks for the library!

**Comment by mukesh-simform** [comment]
We've recently released a new version that should address the issue, Please try using the new version. if you continue to encounter the issue, feel free to reopen the existing ticket or create a new one

**Comment by KodDaniel** [comment]
I will try this and report back if it works. Thanks for the quick handling!
