### ISSUE TITLE
[BUG] The onPress/onLongPress function is not being called on Android >= 12

### ISSUE THREAD

**Issue by yubin-gurzu** [SimformSolutionsPvtLtd/react-native-reactions#43]
The mentioned functions are not working in Android 13 specifically. One case we had, the onPress was working but the onLongPress wasn't. 

It's working fine on lower Android versions and iOS.

**Comment by kuldip-simform** [comment]
@yubin-gurzu 
Thank you for bringing this to our notice.
Can you please provide a bit more information about this or a minimum reproducible example so that we can deduce this from our end or you can provide a code sample from your project where this feature is not working? 

This will help us investigate the issue better.

**Comment by yubin-gurzu** [comment]
Of course. Here's a little code snippet on how we're using it.

```
<Reaction
      type="default"
      showPopupType="onPress"
      onPress={() => console.log("On pressing reaction")}
      items={ReactionItems}
      onTap={() => console.log("On tap reaction")}
      iconSize={heightToDp(emojiSize)}
      titleStyle={STYLES.transparent}
      titleBoxStyle={STYLES.transparent}
      onLongPress={() => console.log("Long pressing reaction")}
      scaleDuration={500}
      cardDuration={300}>
            <Emoji
              name={getEmojiIcon(selectedEmoji || "heart")}
              style={{ fontSize: widthToDp(selectedEmojiSize) }}
            />
</Reaction>
```

The default icon is pressed to show the list of emojis and on selecting any emoji, the onTap function is fired on any other Android version. But this issue is specific to Android 13. 

Please let us know if we're missing anything for Android 13. Thanks a lot for your time.

**Comment by yubin-gurzu** [comment]
Here's a [reproducible example](https://github.com/yubinkarki/Reactions-Android-13-Issue). We have confirmed that the onPress functions are not being called in an Android 13 device but works well on devices with lower Android versions (11, 12). Please look into it. Thank you.

**Comment by kuldip-simform** [comment]
@yubin-gurzu Thank you for providing reproducible example repo. we are looking into this.

**Comment by yubin-gurzu** [comment]
@kuldip-simform Any updates on this? Do let us know your findings.

**Comment by Etaliya** [comment]
Any update guys?

**Comment by kuldip-simform** [comment]
@Etaliya @yubin-gurzu We are looking into this. The primary conclusion is that the panhandler is affecting touchable opacity's onPress event.
We are actively working on this issue. 

We will post here once we have further information.

**Comment by efstathiosntonas** [comment]
@kuldip-simform maybe import `TouchableOpacity` from 'react-native-gesture-handler` instead of `react-native`?

**Comment by rjuevesano** [comment]
any updates?
