### ISSUE TITLE
Using on top of bottom sheet, reactions are not selected. Need to click again to enable the reactions

### ISSUE THREAD

**Issue by aditijain2606** [SimformSolutionsPvtLtd/react-native-reactions#50]
I'm using reactions with bottom sheet. When I long press on button, the modal is opened but I'm not able to select any emoji. I have to release the press and then long press again on the emoji to select it.
It is working fine on normal screen. But with bottom sheet I'm facing this issue.
Any suggestions how I can fix this? Please, I need it urgently

**Comment by dhruv-h-simform** [comment]
@aditijain2606 Thank you for bringing up the question.

Can you share insights into the issue that you are facing? it would be better if you shared a code snippet.
