### ISSUE TITLE
[Q] How do i use the reactions bar directly?

### ISSUE THREAD

**Issue by anniewey** [SimformSolutionsPvtLtd/react-native-reactions#51]
I want to have a slider emoji right on display, without having to long press on single text `Like` to pop up. 
The 6 emoji will be shown by default and user can slide/choose any of the emoji, same like what you have now.

Simple usage like below doesnt work, unless i copied the entire `<Card/>`:
```
const ReactionItems = [
  {
    id: 0,
    emoji: '😇',
    title: 'like',
  },
  {
    id: 1,
    emoji: '🥰',
    title: 'love',
  },
  {
    id: 2,
    emoji: '🤗',
    title: 'care',
  },
  {
    id: 3,
    emoji: '😘',
    title: 'kiss',
  },
  {
    id: 4,
    emoji: '😂',
    title: 'laugh',
  },
  {
    id: 5,
    emoji: '😎',
    title: 'cool',
  },
];

    return (
      <View style={{flex:1}}>
        <Reaction items={ReactionItems} onTap={setSelectedEmoji}>
          <Text>{selectedEmoji ? selectedEmoji?.emoji : 'Like'}</Text>
        </Reaction>
      </View>
    );
```

**Comment by aamirpaddercrowdbotics** [comment]
You need to wrap your component with **ReactionProvider** like below
`<ReactionProvider>
{your JSX here}
</ReactionProvider>`

**Comment by mukesh-simform** [comment]
Current version doesn't support this, Reactions popup will be only visible with press and long press, Thanks!

**Comment by milicedin** [comment]
@mukesh-simform  is there anything on the roadmap to support manually opening the reactions modal?
It isn't possible to use the reactions to an image that is under a touchableopacity because the opacity steals the event
